# Generated by Django 4.1.9 on 2023-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_cartproduct_cart_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartproduct',
            name='unique_cart_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
