# Generated by Django 4.1.9 on 2023-07-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_cartproduct_unique_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order',
            new_name='cart',
        ),
    ]
