# Generated by Django 4.1.9 on 2023-08-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='cart',
            new_name='order',
        ),
    ]
