# Generated by Django 4.1.9 on 2023-08-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_rename_cart_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
