# Generated by Django 4.1.9 on 2023-08-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=100000),
            preserve_default=False,
        ),
    ]
