# Generated by Django 4.1.9 on 2023-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=200000),
            preserve_default=False,
        ),
    ]
