# Generated by Django 4.1.9 on 2023-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_rating_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_feedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
