# Generated by Django 4.1.9 on 2023-09-04 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0012_alter_rating_feedback_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating_feedback',
            unique_together={('user', 'product')},
        ),
    ]
