# Generated by Django 4.1.9 on 2023-09-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_rating_feedback_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating_feedback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating_feedback',
            name='commented',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.rating_feedback'),
        ),
        migrations.AlterField(
            model_name='rating_feedback',
            name='feedback',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rating_feedback',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='rating_feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('commented', None)), fields=('user', 'product'), name='parent'),
        ),
    ]
