# Generated by Django 4.1.9 on 2023-09-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_rating_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating_feedback',
            name='parent',
        ),
        migrations.AlterField(
            model_name='rating_feedback',
            name='commented',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comment', to='operations.rating_feedback'),
        ),
        migrations.AddConstraint(
            model_name='rating_feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('commented', None)), fields=('user', 'product'), name='Checking the existence of a parent'),
        ),
    ]
