# Generated by Django 4.1.9 on 2023-09-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_alter_rating_feedback_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.product')),
            ],
        ),
    ]
